import Footer from "@web/components/Footer/Footer";
import styles from "@web/styles/Home.module.css";
import classNames from "classnames/bind";
import { NextPage } from "next";
import Head from "next/head";
import { SWRConfig } from "swr";
import Contact from "./components/Contact";
import Header from "./components/Header";
import Me from "./components/Me";
import Review from "./components/Review";
import Services from "./components/Services";
import Carousel from "@web/components/Carousel/Carousel";

const cn = classNames.bind(styles);

type Props = {
  fallback: any;
};

const Home: NextPage<Props> = ({ fallback }) => {
  return (
    <SWRConfig value={{ fallback }}>
      <Head>
        <title>Real Estate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="bg-[#fdf8ff]">
          <div className={cn("container")}>
            <Header />
          </div>
        </div>
        <div className="py-[50px] sm:py-[100px] bg-gradient-to-b from-[#FFF5F3] to-[#fff5f3]">
          <h2 className="section-title mb-5 md:mb-8">Объекты</h2>
          <Carousel />
          <Services />
        </div>
        <Me />
        <Contact />
        <Review />
        <Footer />
      </main>
    </SWRConfig>
  );
};

export default Home;
